### ISSUE TITLE
Testeo

### ISSUE THREAD

**Issue by juanAFernandez** [freelinuxdistrodeployed/LDT#10]
Como parte del desarrollo debemos testear las partes del proyecto de forma local. Para ello debemos hacer uso de jaulas o contenedores. Creando varias donde hacer el despliegue de Ansible. Dentro de estas jaulas o contenedores tendremos que configurar lo mínimo par que Ansible pueda conectarse a ellas con SSH. Tendremos que investigar sobre ello.

**Comment by juanantc** [comment]
Movido a #22
