### ISSUE TITLE
Script de instalación del Servidor

### ISSUE THREAD

**Issue by JA-Gonz** [freelinuxdistrodeployed/LDT#12]
- Script principal: Instalación de todo en el servidor. 

-Ansible
-MongoDB
-Apache
-Django
-Python

Cuando instaléis algo en el servidor, por favor, poned la lista de todo lo que instaleis aquí (sus nombres de paquetes). Todos los paquetes instalados y descritos en este issue serán los que se metan en el script final de instalación, así que no podemos dejarnos nada!

**Comment by juanantc** [comment]
Tarea realizada [install.sh](https://github.com/freelinuxdistrodeployed/LDT/blob/master/install.sh)
