### ISSUE TITLE
Interfaz web del servidor

### ISSUE THREAD

**Issue by JA-Gonz** [freelinuxdistrodeployed/LDT#13]
-Preparación de la Web (Simple):La web será una interfaz entre Alberto (o el admin) y el servidor.  Funcionalidades que debe tener: 

1. Que desde un botón se ejecute un script en el servidor. La salida se verá en la web

Más adelante, iremos añadiendo maás funcionalidades al Issue conforme vamos viendo

**Comment by juanantc** [comment]
Se descarta el uso de interfaz web del servidor en nuestra entrega del proyecto
