### ISSUE TITLE
Creacion de pruebas con Dockerfile

### ISSUE THREAD

**Issue by JA-Gonz** [freelinuxdistrodeployed/LDT#16]
La automatización de la creación de imágenes de pruebas está en el script InstalarDocker.sh que tenemos dentro de la carpeta test. Para la construcción del entorno, si es necesario pasar más archivos al contenedor (como por ejemplo, recursos de afuera, como scripts u otros archivos) se hace mediante la orden ADD.

Esto presenta un problema: si la construcción utiliza un Dockerfile leido desde la STDIN (es decir, ejecutamos "sudo docker build - < Dockerfile", que es el ejemplo que encontramos en todos sitios), la orden ADD no funciona (bueno, solo funciona con URL de internet, no con paths de nuestra máquina). Así que podemos subir nuestros recursos a algun sitio web y proporcionarlo en una URL (versión chapuza), o bien, comprimir en un mismo archivo XXXXX.tar.gz todos los recursos que necesitamos, junto al Dockerfile, y de esta forma si funcionará.

E ejemplo es claro: si utilizo:
sudo docker build - < Dockerfile

y estoy intentando añadir por ejemplo un script (LDT.sh), y quiero que se ejecute, no funcionará. En su defecto, debo comprimir el DOckerfile y LDT.sh en un mismo archivo XXX.tar.gz, e introducir la orden:

sudo docker build - < XXX.tar.gz

Y ya solo queda ejecutar la máquina (ojo con la opción -i a la hora de ejecutar!)

**Comment by juanantc** [comment]
Movido a #22
