### ISSUE TITLE
Especificar licencia del proyecto.

### ISSUE THREAD

**Issue by juanAFernandez** [freelinuxdistrodeployed/LDT#18]
Estamos desarrollando el proyecto pero aún no hemos especificado la licencia. Debemos de definir una que se ajuste al nuestro. Por ahora tenemos por defecto (al ser el código público) la de propiedad con libre distribución.

**Comment by JA-Gonz** [comment]
No se si hay que hacerlo especificando en cada archivo su licencia (lo cual lo veo un poco tedioso), o bien, si en el directorio principal (de ambas ramas), podemos poner la licencia abierta, y "que se aplica al resto de subcarpetas". 

Igualmente, creo que si no se especifica nada, tengo entendido que es todo lo contrario: no estás dando tu permiso para su distribución (es decir, privado hasta que no se especifique lo contrario). Por lo que ahora mismo, nadie podría utilizar nuestro código; todos los derechos están reservados. Es lo que recuerdo de la charla de psicobyte, pero también he encontrado algo al respecto:

http://www.genbetadev.com/software-libre-y-licencias/github-finalmente-se-toma-en-serio-la-inclusion-de-licencias-en-los-repositorios

Por lo que hay que meter una licencia OSI, pero ya digo, desconozco como hay que hacerlo (el dónde y cómo alojar la licencia, la licencia en sí es un copiar-pegar de otras licencias :-) )

**Comment by JA-Gonz** [comment]
La licencia de apache ya está colocada. A fin de cuentas, es la que permitimos que se utilice como quiera nuestro software, pero manteniendo nosotros los derechos de patente. Está colocada tal y como explica en esta página, que es a la que referencia Github para añadir licencias a los repositorios:

http://choosealicense.com/licenses/apache-2.0/

Por tanto, creo que podemos pegar carpetazo al asunto.

**Comment by juanAFernandez** [comment]
Entiendo que se pueda utilizar el código como se quiera, pero ¿que pasa con la autoría?, ¿se mantiene?.

**Comment by JA-Gonz** [comment]
Eso siempre, una cosa es que demos permisos de uso, y otra distinta que nos plagien. Es como cuando te contrata una empresa. En tu contrato, estas cediendo los derechos de explotación de tus códigos a dicha empresa, pero la autoría es tuya, y eso nadie te la puede quitar.

**Comment by JA-Gonz** [comment]
Por cierto he editado el comentario de antes, corrigiendo un error en el tema de las patentes.
