### ISSUE TITLE
Obtener IP con netifaces

### ISSUE THREAD

**Issue by mortega87** [freelinuxdistrodeployed/LDT#19]
He subido un fichero para obtener la IP del host especificando una interfaz concreta, pero para ejecutarlo hay que importar netifaces, el cual hay que instalarlo. Netifaces es un paquete que hay que descargar desde su web, hay que ver si se puede hacer desde linea de comandos porque si hay que descargar el paquete es un inconveniente.

Dejo la web de netifaces: https://pypi.python.org/pypi/netifaces

**Comment by juanAFernandez** [comment]
Siempre se puede hacer con [wget](http://es.wikipedia.org/wiki/GNU_Wget) y la dirección donde se encuentra el archivo. Genial que hayas hecho que funcione!

**Comment by JA-Gonz** [comment]
Mirad esta página:

http://packages.ubuntu.com/search?keywords=python-netifaces

Los paquetes que resuelven el problema son python-netifaces y python-netifaces-dbg (esta en su versión de deupración). Ya instalamos la más conveniente, pero poder se puede parece ser. He instalado los dos paquetes en mi portátil y los pilla. Quizás eso es lo que andamos buscando.

**Comment by juanAFernandez** [comment]
Al realizar la conexión con el server a través del socket se conoce la ip del host que hace la conexión, me acabo de dar cuenta y no hace falta enviar la IP del host porque ya la tenemos en la variable addr, así que no será necesario usar la librería ni ninguna otra herramienta.
Este es un extracto de [client.py](https://raw.githubusercontent.com/freelinuxdistrodeployed/LDT/master/envioInfoClienteServidor/server.py) donde hace lo que comento:

~~~bash
c, addr=s.accept();

    print 'Servidor: Recibida conexion desde:',addr
    #En addr ya tenemos la ip del cliente, solo nos falta el nombre.
~~~
