### ISSUE TITLE
Configuración de host con configHost.sh y decisiones de seguridad

### ISSUE THREAD

**Issue by juanAFernandez** [freelinuxdistrodeployed/LDT#20]
Hay que crear un fichero **configHosts.hs** (p.e.) que se ejecute en las máquinas clientes y que configuren lo mínimo para que se pueda desplegar de forma automática. Debería crear un usuario especial con el que ansible se conectará, como ansibleUser (**aquí por seguridad debemos pensar en si debe tener contraseña, quién la establece y como se hace**), después debe copiarse la clave del server en el fichero authorized para que se pueda conectar sin clave y luego ejecutar el script de python client.py que conecta con el server para que coja la ip.

Esqueleto: [configHost.sh](https://raw.githubusercontent.com/freelinuxdistrodeployed/LDT/master/configHost.sh)

No olvidéis referenciar los commit a una issue concreta con #issue !!

**Comment by juanantc** [comment]
Se ha conseguido que funcione #24
