### ISSUE TITLE
HitoFinal IV P4 Sección B: Testing

### ISSUE THREAD

**Issue by juanAFernandez** [freelinuxdistrodeployed/LDT#22]
Participación en los scripts y diferentes formas de testeo. Relacionad todo lo que hagáis referente a esto con #22 en los commits. Recordad que tenemos que participar todos.

**Comment by JA-Gonz** [comment]
Las versiones finales de testing están subidas en el siguiente commit (por un error en el commit no he podido referenciarlo)

https://github.com/freelinuxdistrodeployed/LDT/commit/1ced9306279e9daa46cfee5fe9c547dfb7c89f23

**Comment by juanAFernandez** [comment]
Terminada la sección de testing  a fecha de entrega del proyecto se cierra el issue.
