### ISSUE TITLE
HitoFinal IV P4 Sección C: Configuración de integración continua y PaaS

### ISSUE THREAD

**Issue by juanAFernandez** [freelinuxdistrodeployed/LDT#23]
Participación en todo lo relacionado al tema. Relacionad todo lo que hagáis referente a esto con #23 en los commits. Recordad que tenemos que participar todos.
Algunos enlaces:
[1](http://es.wikipedia.org/wiki/Integraci%C3%B3n_continua) [2](http://www.javiergarzas.com/2014/08/implantar-integracion-continua.html) [3](http://www.mtp.es/noticias/290-integracion-continua-la-solucion-para-afrontar-con-exito-entornos-de-desarrollo-complejos)
En el último puede verse resumido lo que serían las claves:

La práctica de Integración Continua permite:

*Mantener un único repositorio de código fuente.
*Automatizar la construcción del proyecto.
*Hacer que la construcción del proyecto ejecute sus propios tests.
*Entregar los cambios a la línea principal todos los días.
*Construir la línea principal en la máquina de integración.
*Mantener una ejecución rápida de la construcción del proyecto.
*Probar en una réplica del entorno de producción.
*Hacer que todo el mundo pueda obtener el último ejecutable de forma fácil.
*Publicar qué está pasando.
*Automatizar el despliegue.

El problema es que nuestro proyecto es peculiar y no estamos desarrollando una aplicación en sí con lo que no podemos usar programas como [Travis CI](http://www.genbetadev.com/sistemas-de-control-de-versiones/travis-ci-sistema-distribuido-de-integracion-continua-libre-integrado-con-github) para gestionar la integración continua. Tenemos que buscar una forma de adaptarnos.

**Comment by mortega87** [comment]
Ya que estamos utilizando como PaaS para la aplicación Microsoft Azure, he creado un post de configuración, y posteriormente crearé uno que automatice el proceso de instalación de las maquinas virtuales.

**Comment by mortega87** [comment]
Creado script para instalar automaticamente el entorno virtual de Azure, con una maquina server y tres clientes. Para lanzar este script, previamente hay que sincronizar la cuenta con el equipo desde el que se lanza este script, ver el post que comentaba anteriormente, ya que ese proceso es imposible de hacer automatizado.

**Comment by juanAFernandez** [comment]
¿@mortega87  has probado a instalar el **[azure-client](http://azure.microsoft.com/es-es/documentation/articles/command-line-tools/)** en Linux? Lo he intentado de varias maneras y no consigo nada.

**Comment by mortega87** [comment]
Todos los pasos a seguir los puse en el post, siguiendolos me funciona todo corrrectamente

**Comment by juanAFernandez** [comment]
Valoradas las posibilidades y opciones de la integración continua entre los compañeros y añadido en la documentación web, terminada la configuración del despliegue de las máquinas de forma automática en Azure se cierra el issue.
