### ISSUE TITLE
Fecha Defensa Proyecto

### ISSUE THREAD

**Issue by juanAFernandez** [freelinuxdistrodeployed/LDT#25]
Hay que elegir una fecha para la defensa, comentad vuestra preferencia:

* 10 Febrero
* 11 Febrero

**Comment by JA-Gonz** [comment]
Me da igual la verdad. Si acaso, 11 por el tema de tener 1 día más para pulir fallos.

**Comment by juanAFernandez** [comment]
Perfecto

*Juan Antonio Fernández Sánchez*
*E.T.S. de Ingenierías Informática y de Telecomunicación | Universidad de
Granada*
*Correo: *juan.antonio.fernandez.sanchez.88@gmail.com | *Tfno*: 677164459
<https://webmailest.ugr.es/?_task=mail&_action=show&_uid=1933&_mbox=INBOX&_search=b73a064aeb6f163755601057b110b2bd>

2015-01-28 19:16 GMT+01:00 JA-Gonz <notifications@github.com>:

**Comment by juanAFernandez** [comment]
Entonces queda fechada para el día 11.

**Comment by JA-Gonz** [comment]
Notificando a @JJ la fecha d proyecto. Será el día 11 después de haberlo hablado todos.
