### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by JA-Gonz** [freelinuxdistrodeployed/LDT#27]
Llegados a este punto, tenemos que hacer la presentación para el próximo día 11 de febrero, como ya hablamos.

Necesitamos utilizar una herramienta que convierta fácilmente los archivos .md a paginas en una presentación que pueda hacerse on-line (como la conversión de los md que hace @JJ a la página de la asignatura). Hay alguna herramienta por ahí porque esto lo ha comentado el en clase, pero necesitamos centrarnos en alguna en concreto y aprender a usarla, como hicimos con Jekyll para la web!

**Comment by JJ** [comment]
Podéis usar reveal.js, tiene una opción para poner los datos en .md

El 4 de febrero de 2015, 12:01, JA-Gonz <notifications@github.com> escribió:

> Llegados a este punto, tenemos que hacer la presentación para el próximo
> día 11 de febrero, como ya hablamos.
>
> Necesitamos utilizar una herramienta que convierta fácilmente los archivos
> .md a paginas en una presentación que pueda hacerse on-line (como la
> conversión de los md que hace @JJ <https://github.com/JJ> a la página de
> la asignatura). Hay alguna herramienta por ahí porque esto lo ha comentado
> el en clase, pero necesitamos centrarnos en alguna en concreto y aprender a
> usarla, como hicimos con Jekyll para la web!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freelinuxdistrodeployed/LDT/issues/27>.
>



-- 
JJ

**Comment by juanAFernandez** [comment]
@JA-Gonz reveal.js está muy bien, hay alguna opción más?

**Comment by JA-Gonz** [comment]
Pandoc parece que tiene alguna opción parecida también,  al igual que Cleaver. De Cleaver he encontrado un [mini tutorial](http://blog.g3ortega.com/2013/09/clever-crea-una-presentacion-usando.html#.VNJHEC6ldFU), al igual que de Reveals.js [hay otro](http://www.ciges.net/presentaciones-buenas-bonitas-y-baratas-y-facilitas-en-html5-con-revealjs). Pero vamos, mañana me bajo los dos, y miro cuál gana la relación facilidad - apariencia :dancer:

**Comment by juanAFernandez** [comment]
Estoy revisando reverals, está muy bien. Y tiene una opción interesante para pasar todas las diapositivas con .md pero para eso hay que tenerlo corriendo en un servidor web con node.js instalado  y Grunt (necesita node.js en versión 0.10 min). Podríamos instalarlo en el servidor y que los .md de cada diapositiva estén en el repositorio o hacer la edición directamente en el index.html del proyecto básico que bajas al hacer clone. Como prefiráis.

**Comment by JJ** [comment]
Si no usáis MD se mete en HTML. Tampoco es tan complicado.

El 8 de febrero de 2015, 13:09, Juan Antonio <notifications@github.com>
escribió:

> Estoy revisando reverals, está muy bien. Y tiene una opción interesante
> para pasar todas las diapositivas con .md pero para eso hay que tenerlo
> corriendo en un servidor web con node.js instalado y Grunt (necesita
> node.js en versión 0.10 min). Podríamos instalarlo en el servidor y que los
> .md de cada diapositiva estén en el repositorio o hacer la edición
> directamente en el index.html del proyecto básico que bajas al hacer clone.
> Como prefiráis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freelinuxdistrodeployed/LDT/issues/27#issuecomment-73408190>
> .
>



-- 
JJ

**Comment by mortega87** [comment]
@JJ A que hora y en que aula son las presentaciones?

**Comment by juanAFernandez** [comment]
En el servidor ya está funcionando reveal (ha sido necesario abrir un puerto desde Azure para que se pudiera conectar). Para que la presentación funcione hay que hacer **grunt serve** dentro de la rama presentación y dentro del repositorio. Una vez hecho ya podemos acceder a esta usando **http://servermachine2015.cloudapp.net:8000**
