### ISSUE TITLE
Petición de tutoría

### ISSUE THREAD

**Issue by JA-Gonz** [freelinuxdistrodeployed/LDT#28]
Hola @JJ

A @juanantc y a mi nos gustaría poder quedar en tu despacho para ver si podemos aclarar algunas cosillas de las notas finales (¡demonios! ¡que estamos suspensos!). ¿Podríamos quedar algún día de estos para ver si hay forma de solucionar esto?

Muchas gracias de antemano

**Comment by JJ** [comment]
A ver, ¿por qué diablos no entregáis los objetivos correspondientes al
último hito, sin los cuales ya os dije que éste estaba suspenso?

El 13 de febrero de 2015, 12:14, JA-Gonz <notifications@github.com>
escribió:

> Hola @JJ <https://github.com/JJ>
>
> A @juanantc <https://github.com/juanantc> y a mi nos gustaría poder
> quedar en tu despacho para ver si podemos aclarar algunas cosillas de las
> notas finales (¡demonios! ¡que estamos suspensos!). ¿Podríamos quedar algún
> día de estos para ver si hay forma de solucionar esto?
>
> Muchas gracias de antemano
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freelinuxdistrodeployed/LDT/issues/28>.
>



-- 
JJ

**Comment by JJ** [comment]
y @ja-gonz está suspenso básicamente por el 0 en el segundo hito del
proyecto. Ya di varias oportunidades para que se corrigiera.

El 13 de febrero de 2015, 12:18, JJ Merelo <jjmerelo@gmail.com> escribió:

> A ver, ¿por qué diablos no entregáis los objetivos correspondientes al
> último hito, sin los cuales ya os dije que éste estaba suspenso?
>
> El 13 de febrero de 2015, 12:14, JA-Gonz <notifications@github.com>
> escribió:
>
> Hola @JJ <https://github.com/JJ>
>>
>> A @juanantc <https://github.com/juanantc> y a mi nos gustaría poder
>> quedar en tu despacho para ver si podemos aclarar algunas cosillas de las
>> notas finales (¡demonios! ¡que estamos suspensos!). ¿Podríamos quedar algún
>> día de estos para ver si hay forma de solucionar esto?
>>
>> Muchas gracias de antemano
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/freelinuxdistrodeployed/LDT/issues/28>.
>>
>
>
>
> --
> JJ
>



-- 
JJ

**Comment by JA-Gonz** [comment]
Probablemente cuando se habló ese tema fue un Lunes, estando yo de prácticas de empresa. Pero bueno, entregué los ejercicios que le hito 2  pedía, ese 0 lo achaqué a la nula participación que tuve por aquel entonces en el proyecto. Por lo que por eso me puse las pilas de ahi en adelante. En el tercer hito y con los 0 de algunos de los compañeros, si mal no recuerdo, se hablaba de que haciendo cosas de ese hito, se tenía la oportunidad de remontar ese 0 (a menos nota, claro está). 

Me hace falta 0.5 sólo para aprobar, y es que con los ejercicios que tnego, el haber seguido la asignatura (después del pinchazo), y haber hecho también la presentación del proyecto, ¿no puedo sacarlo de ningún sitio?

**Comment by JJ** [comment]
Me tienes que hacer un enlace a los commits donde arreglaras lo de esa
segunda práctica.

El 13 de febrero de 2015, 12:31, JA-Gonz <notifications@github.com>
escribió:

> Probablemente cuando se habló ese tema fue un Lunes, estando yo de
> prácticas de empresa. Pero bueno, entregué los ejercicios que le hito 2
> pedía, ese 0 lo achaqué a la nula participación que tuve por aquel entonces
> en el proyecto. Por lo que por eso me puse las pilas de ahi en adelante. En
> el tercer hito y con los 0 de algunos de los compañeros, si mal no
> recuerdo, se hablaba de que haciendo cosas de ese hito, se tenía la
> oportunidad de remontar ese 0 (a menos nota, claro está).
>
> Me hace falta 0.5 sólo para aprobar, y es que con los ejercicios que
> tnego, el haber seguido la asignatura (después del pinchazo), y haber hecho
> también la presentación del proyecto, ¿no puedo sacarlo de ningún sitio?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freelinuxdistrodeployed/LDT/issues/28#issuecomment-74240701>
> .
>



-- 
JJ

**Comment by JA-Gonz** [comment]
No tengo commits que reflejen mi participación en ese hito, la verdad. Sé que hubo reestructuraciones en el proyecto, y también participé con los playbooks de cara a la entrega final (y en la presentación "en vivo" de los 3 hosts con el servidor funcionando, todos en Azure). He tenido que tocar bastantes cosas de cara a hacer algunos scripts (como el de añadir usuarios a sudoers que permita la instalación mediante ansibleUser) dentro de las propias máquinas de Azure. No tengo commits que lo reflejen, insisto, pero a raíz de ese 0, quise ponerme al día. No aporté nada nuevo en ese hito por que los compañeros ya levantaron esas máquinas en Azure, pensé que no había nada nuevo que aportar.

La práctica 4 utiliza todo lo que hay de antes, es obvio que he trabajado con las cosas que se piden en la práctica 2, pero entiendo que no pueda ser evaluado al no tener commits y no estar en GitHub. ¿No me cuenta en este caso la presentación o los ejercicios?

**Comment by JA-Gonz** [comment]
...

O el haber trabajado con la P2 y saber como funciona de primera mano.

**Comment by juanantc** [comment]
Acabo de subir mi fichero de objetivos

**Comment by juanantc** [comment]
[Objetivos](https://github.com/JJ/GII-2014/pull/697)

**Comment by JJ** [comment]
@ja-gonz no puedo hacer nada. Tienes sólo 9 contribuciones a ejercicios,
una de las cuales es borrar un ~ En la práctica no tienes ni siquiera un
commit hasta el 25 de noviembre. Tampoco has asistido ni a la cuarta parte
de las clases, así que sintiéndolo mucho, te mantengo la nota. Las segundas
oportunidades de cada una de las prácticas no solo las dije en clase, sino
que las envié a la lista de correo. Te habría bastado un 5 en esa práctica
para aprobar a asignatura (donde te he dado un 0.5 por trabajo autónomo,
por cierto, que figura en la columna correspondiente). Así que lo siento.
Con la nota que tienes en junio tienes aproximadamente un punto sobre 2 en
septiembre. El examen puntuará sobre 8.

**Comment by JA-Gonz** [comment]
Las clases que yo tenga entendido, eran voluntarias. De hecho, recuerdo sus palabras de la presentación de la asignatura, en la que contaba con "ausentismo escolar voluntario, que si no, tendrá que ser forzado por el aforo". Yo he tenido prácticas de empresa hasta diciembre y de ahí mi limitada asistencia a clase, más aún cuando a final de prácticas toca achuchar (por que te vas en 1 mes). De haber sabido que las clases si que contaban, quizás me hubiera adaptado de otra forma a la situación.

Los ejercicios los hago del tirón todos y los subo, tengo esa metodología, de ahí los 9 commits y no los 900. Pero los ejercicios están.

Me habría bastado un 5 en esa práctica (cuyos contenidos he tenido que manejar, conocer y aprender para la práctica 4, insisto). En el 0.5 de nota de clase imagino que ya va incrustada la nota adicional de presentación, lo que me deja un poco perplejo que la nota real de clase me sea tan baja.

En definitiva, creo que se me está suspendiendo por tecnicismos, no por que no haya trabajado. Pero en fin, nos vemos en septiembre si así lo quieres.

**Comment by JJ** [comment]
El 13 de febrero de 2015, 14:43, JA-Gonz <notifications@github.com>
escribió:

> Las clases que yo tenga entendido, eran voluntarias. De hecho, recuerdo
> sus palabras de la presentación de la asignatura, en la que contaba con
> "ausentismo escolar voluntario, que si no, tendrá que ser forzado por el
> aforo". Yo he tenido prácticas de empresa hasta diciembre y de ahí mi
> limitada asistencia a clase, más aún cuando a final de prácticas toca
> achuchar (por que te vas en 1 mes). De haber sabido que las clases si que
> contaban, quizás me hubiera adaptado de otra forma a la situación.
>

El  hecho de que un 40% se considerara "nota de clase" debería haberte dado
una pista.

> Los ejercicios los hago del tirón todos y los subo, tengo esa metodología,
> de ahí los 9 commits y no los 900. Pero los ejercicios están.
>

Claro. Una metodología que, creo que lo he dejado muy claro, no merece la
máxima nota en ese apartado.

> Me habría bastado un 5 en esa práctica (cuyos contenidos he tenido que
> manejar, conocer y aprender para la práctica 4, insisto). En el 0.5 de nota
> de clase imagino que ya va incrustada la nota adicional de presentación, lo
> que me deja un poco perplejo que la nota real de clase me sea tan baja.
>
> En definitiva, creo que se me está suspendiendo por tecnicismos, no por
> que no haya trabajado. Pero en fin, nos vemos en septiembre si así lo
> quieres.
>

Te estás suspendiendo tú mismo por el 0 que has tenido en la segunda
práctica y que no has intentado recuperar a pesar de las diversas
oportunidades que os he dado a lo largo de la asignatura. Pero puedes
entenderlo como quieras.
