### ISSUE TITLE
Definiciones de funcionalidades 

### ISSUE THREAD

**Issue by mortega87** [freelinuxdistrodeployed/LDT#7]
En este Issue vamos a exponer las funcionalidades necesarias para el proyecto.

1. Instalar programas.
2. Eliminar programas
3. Consultar programas instalados en los host. ==> OK
4. Consultar hardware de host. ==> OK
5. Consultar los logs.
6. Consultar que ejecutan los host en cada momento (Monitorización) (javascript y ajax para refresco automatico).*
7. Librerias graficas para apartado 6.*
8. Consultar instalaciones realizadas por el usuario.*
9. Conocer enlace que navega en tiempo real cada host.*
10. Envio de mensajes emergentes en escritorio de los hosts.* ==> OK (falta probar)

11.Red (vnstat)

*Objetivos para investigar una vez que esten terminados los anteriores.

**Comment by juanantc** [comment]
Instalar programas. *[x]
    Consultar programas instalados en los host. *[x]
    Consultar hardware de los hosts. *[x]
    Consultar los logs. *[x]
    Envio de mensajes emergentes en escritorio de los hosts. *[x]
